name: Publish Docker image

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1.2.2
        repo: venkatamutyala/testing-actions
        workflow: main.yaml
        
