name: Publish Docker image

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3


      - uses: pauldraper/workflow-dispatch@v1.5
        with:
          ref: main
          repo: venkatamutyala/testing-actions
          token: ${{ secrets.PAT_TOKEN }}
          wait: "true"
          inputs: '{ "manifest_to_update": "test-app-values.yaml", "tag":"${{ github.sha }}" }''
          workflow: main.yaml
