name: Publish Docker image

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          repo: venkatamutyala/testing-actions
          workflow: main.yaml
          token: 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
          ref: main

